# Generated by Django 4.2.11 on 2024-03-05 14:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidder', '0001_initial'),
        ('advertiser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_fee', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('availability', models.BooleanField(default=False)),
                ('advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interest_groups', to='advertiser.advertiser')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interest_groups', to='bidder.bidder')),
            ],
        ),
        migrations.AddConstraint(
            model_name='interestgroup',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('advertiser__isnull', True), ('availability', True)), models.Q(('advertiser__isnull', False), ('availability', False)), _connector='OR'), name='advertiser_availability_validation'),
        ),
    ]
